"""
Shopping Agent: LLM-powered shopping assistant with tool calling.

The agent uses tool/function calling to interact with the payment system.
Idempotency keys are generated by this orchestration code, NOT by the LLM.
"""
import json
import uuid
from typing import Optional, List, Dict, Any
from dataclasses import dataclass, field
import os

from anthropic import Anthropic
from openai import OpenAI

from agent.tools import (
    TOOL_DEFINITIONS,
    search_product,
    get_product_details,
    place_order,
    check_order_status,
    generate_idempotency_key,
)


@dataclass
class ConversationContext:
    """Tracks conversation state for idempotency key generation."""
    user_id: str = "00000000-0000-0000-0000-000000000001"
    turn_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    messages: List[Dict[str, Any]] = field(default_factory=list)
    pending_orders: Dict[str, str] = field(default_factory=dict)


class ShoppingAgent:
    """
    LLM-powered shopping agent.
    
    Uses tool calling to search products and place orders.
    Idempotency keys are generated deterministically by this class.
    """
    
    def __init__(self, provider: str = "anthropic"):
        self.provider = provider
        
        if provider == "anthropic":
            self.client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
            self.model = "claude-3-sonnet-20240229"
        else:
            self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
            self.model = "gpt-4-turbo-preview"
        
        self.context = ConversationContext()
    
    def _get_system_prompt(self) -> str:
        return """You are a helpful shopping assistant. You can help users:
1. Search for products
2. Get product details (price, availability)
3. Place orders
4. Check order status

When a user wants to buy something:
1. First search for the product
2. Show them the options with prices
3. Confirm which one they want
4. Place the order

Always confirm the product and quantity before placing an order.
Be helpful and conversational."""
    
    async def _execute_tool(self, tool_name: str, arguments: dict) -> Any:
        """Execute a tool and return the result."""
        if tool_name == "search_product":
            products = await search_product(arguments["query"])
            return [
                {
                    "id": p.id,
                    "name": p.name,
                    "price": p.price,
                    "available": p.available_qty,
                }
                for p in products
            ]
        
        elif tool_name == "get_product_details":
            product = await get_product_details(arguments["product_id"])
            if product:
                return {
                    "id": product.id,
                    "name": product.name,
                    "description": product.description,
                    "price": product.price,
                    "available": product.available_qty,
                }
            return {"error": "Product not found"}
        
        elif tool_name == "place_order":
            product_id = arguments["product_id"]
            quantity = arguments.get("quantity", 1)
            
            idempotency_key = generate_idempotency_key(
                self.context.user_id,
                self.context.turn_id,
                product_id,
            )
            
            self.context.pending_orders[product_id] = idempotency_key
            
            result = await place_order(
                product_id=product_id,
                quantity=quantity,
                idempotency_key=idempotency_key,
                user_id=self.context.user_id,
            )
            
            return {
                "order_id": result.order_id,
                "status": result.status,
                "total": result.total_amount,
                "message": result.message,
            }
        
        elif tool_name == "check_order_status":
            return await check_order_status(arguments["order_id"])
        
        return {"error": f"Unknown tool: {tool_name}"}
    
    async def chat_anthropic(self, user_message: str) -> str:
        """Handle a chat turn using Anthropic Claude."""
        self.context.messages.append({
            "role": "user",
            "content": user_message,
        })
        
        tools = [
            {
                "name": t["name"],
                "description": t["description"],
                "input_schema": t["parameters"],
            }
            for t in TOOL_DEFINITIONS
        ]
        
        while True:
            response = self.client.messages.create(
                model=self.model,
                max_tokens=1024,
                system=self._get_system_prompt(),
                tools=tools,
                messages=self.context.messages,
            )
            
            if response.stop_reason == "end_turn":
                text_content = ""
                for block in response.content:
                    if hasattr(block, "text"):
                        text_content += block.text
                
                self.context.messages.append({
                    "role": "assistant",
                    "content": response.content,
                })
                
                self.context.turn_id = str(uuid.uuid4())
                return text_content
            
            elif response.stop_reason == "tool_use":
                tool_results = []
                
                for block in response.content:
                    if block.type == "tool_use":
                        result = await self._execute_tool(block.name, block.input)
                        tool_results.append({
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": json.dumps(result),
                        })
                
                self.context.messages.append({
                    "role": "assistant",
                    "content": response.content,
                })
                self.context.messages.append({
                    "role": "user",
                    "content": tool_results,
                })
            
            else:
                break
        
        return "I encountered an issue processing your request."
    
    async def chat_openai(self, user_message: str) -> str:
        """Handle a chat turn using OpenAI GPT."""
        self.context.messages.append({
            "role": "user",
            "content": user_message,
        })
        
        tools = [
            {
                "type": "function",
                "function": {
                    "name": t["name"],
                    "description": t["description"],
                    "parameters": t["parameters"],
                },
            }
            for t in TOOL_DEFINITIONS
        ]
        
        messages = [{"role": "system", "content": self._get_system_prompt()}]
        messages.extend(self.context.messages)
        
        while True:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                tools=tools,
                tool_choice="auto",
            )
            
            message = response.choices[0].message
            
            if message.tool_calls is None:
                self.context.messages.append({
                    "role": "assistant",
                    "content": message.content,
                })
                self.context.turn_id = str(uuid.uuid4())
                return message.content or ""
            
            messages.append(message)
            
            for tool_call in message.tool_calls:
                arguments = json.loads(tool_call.function.arguments)
                result = await self._execute_tool(tool_call.function.name, arguments)
                
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": json.dumps(result),
                })
        
        return "I encountered an issue processing your request."
    
    async def chat(self, user_message: str) -> str:
        """Handle a chat turn."""
        if self.provider == "anthropic":
            return await self.chat_anthropic(user_message)
        else:
            return await self.chat_openai(user_message)
    
    def reset(self):
        """Reset conversation context."""
        self.context = ConversationContext()
