"""
Agent tools for the shopping agent.

These are the functions the LLM can call via tool/function calling.
Idempotency keys are generated by the orchestration code, not the LLM.
"""
import hashlib
import uuid
from typing import Optional, List
from dataclasses import dataclass
import httpx

API_BASE_URL = "http://localhost:8000"


@dataclass
class Product:
    id: str
    name: str
    description: str
    price: float
    available_qty: int


@dataclass
class OrderResult:
    order_id: str
    status: str
    total_amount: float
    message: str


def generate_idempotency_key(
    user_id: str,
    conversation_turn_id: str,
    product_id: str,
) -> str:
    """
    Generate a deterministic idempotency key.
    
    This is called by the orchestration code, NOT the LLM.
    Same inputs always produce the same key, ensuring retries are safe.
    """
    data = f"{user_id}:{conversation_turn_id}:{product_id}"
    return f"agent_{hashlib.sha256(data.encode()).hexdigest()[:32]}"


async def search_product(query: str) -> List[Product]:
    """
    Search for products matching the query.
    
    Args:
        query: Search term to find products
        
    Returns:
        List of matching products
    """
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{API_BASE_URL}/api/products")
        response.raise_for_status()
        data = response.json()
    
    query_lower = query.lower()
    products = []
    
    for p in data["products"]:
        if query_lower in p["name"].lower() or (p["description"] and query_lower in p["description"].lower()):
            products.append(Product(
                id=p["id"],
                name=p["name"],
                description=p["description"] or "",
                price=float(p["price"]),
                available_qty=p["available_qty"],
            ))
    
    return products


async def get_product_details(product_id: str) -> Optional[Product]:
    """
    Get detailed information about a specific product.
    
    Args:
        product_id: UUID of the product
        
    Returns:
        Product details or None if not found
    """
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{API_BASE_URL}/api/products/{product_id}")
        
        if response.status_code == 404:
            return None
            
        response.raise_for_status()
        p = response.json()
    
    return Product(
        id=p["id"],
        name=p["name"],
        description=p["description"] or "",
        price=float(p["price"]),
        available_qty=p["available_qty"],
    )


async def place_order(
    product_id: str,
    quantity: int,
    idempotency_key: str,
    user_id: str = "00000000-0000-0000-0000-000000000001",
) -> OrderResult:
    """
    Place an order for a product.
    
    Args:
        product_id: UUID of the product to order
        quantity: Number of units to order
        idempotency_key: Key for idempotent request handling
        user_id: UUID of the user placing the order
        
    Returns:
        Order result with status
    """
    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{API_BASE_URL}/api/orders",
            json={
                "user_id": user_id,
                "items": [{"product_id": product_id, "quantity": quantity}],
            },
            headers={"Idempotency-Key": idempotency_key},
        )
        
        data = response.json()
    
    if response.status_code == 201:
        return OrderResult(
            order_id=data["id"],
            status="confirmed",
            total_amount=float(data["total_amount"]),
            message="Order placed successfully!",
        )
    elif response.status_code == 422:
        return OrderResult(
            order_id=data.get("id", ""),
            status="failed",
            total_amount=float(data.get("total_amount", 0)),
            message="Order failed and was rolled back.",
        )
    else:
        return OrderResult(
            order_id="",
            status="error",
            total_amount=0,
            message=data.get("detail", "Unknown error"),
        )


async def check_order_status(order_id: str) -> dict:
    """
    Check the status of an existing order.
    
    Args:
        order_id: UUID of the order
        
    Returns:
        Order status information
    """
    async with httpx.AsyncClient() as client:
        response = await client.get(f"{API_BASE_URL}/api/orders/{order_id}")
        
        if response.status_code == 404:
            return {"status": "not_found", "message": "Order not found"}
            
        response.raise_for_status()
        data = response.json()
    
    return {
        "order_id": data["id"],
        "status": data["status"],
        "total_amount": float(data["total_amount"]),
        "items": len(data["items"]),
    }


TOOL_DEFINITIONS = [
    {
        "name": "search_product",
        "description": "Search for products by name or description",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The search term to find products",
                }
            },
            "required": ["query"],
        },
    },
    {
        "name": "get_product_details",
        "description": "Get detailed information about a specific product including price and stock",
        "parameters": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "description": "The UUID of the product",
                }
            },
            "required": ["product_id"],
        },
    },
    {
        "name": "place_order",
        "description": "Place an order for a product. This will charge the payment method.",
        "parameters": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string",
                    "description": "The UUID of the product to order",
                },
                "quantity": {
                    "type": "integer",
                    "description": "Number of units to order",
                    "minimum": 1,
                },
            },
            "required": ["product_id", "quantity"],
        },
    },
    {
        "name": "check_order_status",
        "description": "Check the status of an existing order",
        "parameters": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string",
                    "description": "The UUID of the order to check",
                }
            },
            "required": ["order_id"],
        },
    },
]
